name: 'Coding Standards'

on:
    workflow_call:
        inputs:
            php-version:
                description: 'The PHP version to use when running the job'
                default: '8.1'
                required: false
                type: 'string'
            composer-root-version:
                description: 'The version of the package being tested, in case of circular dependencies.'
                required: false
                type: 'string'
            composer-options:
                description: 'Additional flags for the composer install command.'
                default: '--prefer-dist'
                required: false
                type: 'string'

jobs:
    cs-fixer:
        name: 'CS Fixer'
        runs-on: 'ubuntu-latest'

        strategy:
            matrix:
                php-version:
                    - '${{ inputs.php-version }}'

        steps:
            - name: 'Checkout'
              uses: 'actions/checkout@v2'

            - name: 'Setup environment'
              uses: 'shivammathur/setup-php@v2'
              with:
                  coverage: 'none'
                  php-version: '${{ matrix.php-version }}'

            - name: 'Set COMPOSER_ROOT_VERSION'
              run: |
                  echo "COMPOSER_ROOT_VERSION=${{ inputs.composer-root-version }}" >> $GITHUB_ENV
              if: '${{ inputs.composer-root-version }}'

            - name: 'Install dependencies'
              uses: 'ramsey/composer-install@v2'
              with:
                  dependency-versions: 'highest'
                  composer-options: '${{ inputs.composer-options }}'

            - name: 'Run PHP CS Fixer'
              run: 'vendor/bin/php-cs-fixer fix --dry-run'
